name: Robo PS5

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */2 * * *"

jobs:
  pesquisar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar bibliotecas
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4

      - name: Verificar BeautifulSoup
        run: |
          python -c "from bs4 import BeautifulSoup; print('BeautifulSoup OK')"

      - name: Executar robô
        run: |
          python robo.py

      - name: Salvar resultado
        uses: actions/upload-artifact@v4
        with:
          name: resultado-ps5
          path: resultado.json